### ISSUE TITLE
[Crash] 0.7.1a crashes server but not the client

### ISSUE THREAD

**Issue by V1lo4ka** [MrSypz/Crital#11]
**Minecraft Version**
--1.21--

**Mod Loader Version**
--0.15.11--

**Mod Version**
--0.7.1a--

**Screenshots/Videos**
--paste your videos/screenshots--

**Description**
--After update to 0.7.1a server started crashing on boot, client version still works fine--

**Logs**
 --Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for crital.mixins.json:vanillachange.newcrit.LivingEntityMixin from mod crital during activity: [Transform -> Method getNbtFromEquippedSlots()Ljava/util/List; -> INVOKESTATIC -> sypztep/tyrannus/common/util/ItemStackHelper::getNbtCompound:(Lnet/minecraft/class_1799;)Lnet/minecraft/class_2487;]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]--
        and more after in logs

**Comment by MasterZeeVII** [comment]
It really weird when run server in dev envr nothing crash but when run normally it crash and it now fix on 0.7.1b

**Comment by MasterZeeVII** [comment]
https://modrinth.com/mod/crital/version/GgjOZXCa
try this version and let me know is it still crash

**Comment by V1lo4ka** [comment]
It works, thanks for your work ;)
